package com.clinic.bean;
// Generated 22-may-2014 15:59:42 by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


	/**
	 * 
	 */
	private int idUsuario;
	private String nombreCompleto;
	private String pass;
	private String nickName;
	
		
    public int getIdUsuario() {
		return idUsuario;
	}


	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}


	public String getNombreCompleto() {
		return nombreCompleto;
	}


	public void setNombreCompleto(String nombre) {
		this.nombreCompleto = nombre;
	}


	public String getNickName() {
		return nickName;
	}


	public void setNickName(String nickname) {
		this.nickName = nickname;
	}




	public String getPass() {
		return pass;
	}


	public void setPass(String pass) {
		this.pass = pass;
	}




	/**
	 * @param idUsuario
	 * @param nombre
	 * @param pass
	 */
	public Usuario(int idUsuario, String nombre, String nick, String pass) {
		super();
		this.idUsuario = idUsuario;
		this.nombreCompleto = nombre;
		this.nickName = nick;
		this.pass = pass;
	}


	public Usuario() {
    }

	


}


